shim-version: v0.3.10@sha256:825cfafbc6dde8967ac60e44264f4686fcf2ed33fae112ab4b1c69c6673cdc8e
cvm-version: 0.6.0
cpus: 4
memory: 4096

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
