shim-version: v0.3.19@sha256:e67b8cd0ed61d646911414da0faa378320da7e8b162e399f6ee8b263f45f3f8e
cvm-version: 0.6.8
cpus: 4
memory: 8192

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
