shim-version: v0.4.2@sha256:d65f769e37bbe86ffaeef42120c29c4b9de33415fcd7588a9ef7a64f609aa2a3
cvm-version: 0.6.7
cpus: 4
memory: 8192

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
