shim-version: v0.2.14@sha256:24d59ce41ad00a05ab5a37708b0d8b07a7d09abb1b74b75ee4862f688d093949
cvm-version: 0.5.8
cpus: 8
memory: 2048

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
  publish-attestation: false
