shim-version: v0.2.12@sha256:d65e3c19221ce7d3494e72acbef1171144a71caa01a5b9417edd4ae082a4941a
cvm-version: 0.5.6
cpus: 8
memory: 2048

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
  publish-attestation: false
