shim-version: v0.3.15@sha256:fbb08eff2b332098751f02c5829531cdcda5a30820370d58cb201a6c6215e59a
cvm-version: 0.6.7
cpus: 4
memory: 8192

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
