shim-version: v0.3.2@sha256:2bbbf67720a258f8fb92a470f2368215b97fa5ee92afa117d376e776e34e2373
cvm-version: 0.5.11
cpus: 4
memory: 4096
platform: mini_0d_amd
cvmimage-version: cvmimage-v0.0.6
stage0-version: stage0-v0.0.4

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
  publish-attestation: false
